# Generated by Django 4.2.7 on 2025-12-03 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WATER', 'Water'), ('FERTILIZE', 'Fertilize'), ('REPOTTING', 'Repotting'), ('PRUNE', 'Prune'), ('SNOOZE', 'Snooze'), ('SKIPPED_RAIN', 'Skipped (Rain)'), ('PHOTO', 'Photo'), ('NOTE', 'Note')], max_length=20)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('previous_due_date', models.DateField(blank=True, help_text='Stored for undo functionality', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='plant_photos/')),
                ('image_url', models.TextField(blank=True, help_text='External URL to the photo (if not using file upload)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_cover', models.BooleanField(default=False, help_text='Is this the cover photo?')),
            ],
            options={
                'ordering': ['-is_cover', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('WATER', 'Water'), ('FERTILIZE', 'Fertilize'), ('REPOTTING', 'Repotting'), ('PRUNE', 'Prune')], max_length=20)),
                ('frequency_days', models.IntegerField(help_text='Number of days between tasks')),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='plant',
            name='care_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='perenual_id',
            field=models.IntegerField(blank=True, help_text='External link to Perenual API', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.TextField(blank=True, help_text='Deprecated: Use photos instead. Kept for backward compatibility', null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='schedule',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.plant'),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.plant'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Photo associated with this activity (for PHOTO actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.plantphoto'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.plant'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.schedule'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cover_photo',
            field=models.ForeignKey(blank=True, help_text='The cover photo for this plant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_plant', to='api.plantphoto'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('plant', 'task_type')},
        ),
    ]
